name: AlgoSonar

description: A new Flutter project.

publish_to: 'none' # Remove this line if the package is meant to be published

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^2.0.0
  firebase_core: ^1.20.0
  cloud_firestore: ^3.1.12
  http: ^0.15.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
